### ISSUE TITLE
Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. 

### ISSUE THREAD

**Issue by AlexanderKozhevin** [Juyong/CaricatureFace#2]
Traceback (most recent call last):
  File "train.py", line 29, in <module>
    opt.model1_path, opt.model2_path)
  File "/content/CaricatureFace/cariface.py", line 145, in load_model
    ck1 = torch.load(model1_path)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 665, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 156, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 132, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 126, in validate_cuda_device
    device, torch.cuda.device_count()))
RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.

**Comment by RainbowRui** [comment]
Thanks for your attention.
You could try to change codes in lines 145 and 146 of "cariface.py" as below:
`ck1 = torch.load(model1_path, map_location='cuda:0')`
and
`ck2 = torch.load(model2_path, map_location='cuda:0')`
You can modify the number '0' to your existing device.
This may help you.

**Comment by RainbowRui** [comment]
The number must be the same as 'self.device_num'.
