### ISSUE TITLE
An error message is printed when running to train.py.

### ISSUE THREAD

**Issue by kimsaandev** [Juyong/CaricatureFace#45]
(cariface) C:\Users\HERO\git\CaricatureFace>python train.py --no_train
Traceback (most recent call last):
  File "train.py", line 30, in <module>
    model.test()
  File "C:\Users\HERO\git\CaricatureFace\cariface.py", line 273, in test
    for img, landmark, lrecord, vrecord in self.test_loader:
  File "C:\Users\HERO\anaconda3\envs\cariface\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\HERO\anaconda3\envs\cariface\lib\site-packages\torch\utils\data\dataloader.py", line 746, in __init__
    self._try_put_index()
  File "C:\Users\HERO\anaconda3\envs\cariface\lib\site-packages\torch\utils\data\dataloader.py", line 861, in _try_put_index
    index = self._next_index()
  File "C:\Users\HERO\anaconda3\envs\cariface\lib\site-packages\torch\utils\data\dataloader.py", line 339, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "C:\Users\HERO\anaconda3\envs\cariface\lib\site-packages\torch\utils\data\sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "C:\Users\HERO\anaconda3\envs\cariface\lib\site-packages\torch\utils\data\sampler.py", line 62, in __iter__
    return iter(range(len(self.data_source)))
  File "C:\Users\HERO\git\CaricatureFace\datagen.py", line 168, in __len__
    return self.num_samples
AttributeError: 'TestSet' object has no attribute 'num_samples'

**Comment by RainbowRui** [comment]
The program does not find testing images. So you may need to download test data and pretrained model first, following [README.md](https://github.com/Juyong/CaricatureFace#advanced-work).
